server:
    port: 8083

spring:
    jpa:
        show-sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQL10Dialect
        generate-ddl: false
        properties:
            hibernate:
                show_sql=true
        hibernate:
            ddl-auto: update

    redis:
        host: db_redis
        port: 6379

    data:
      redis:
          repositories:
              enabled: true
      mongodb:
          host: db_mongo
          port: 27017

    datasource:
        username: ${DB_USER:postgres}
        password: ${DB_Password:postgres}
        url: jdbc:postgresql://db_postgres:5445/postgres
        driver-class-name: org.postgresql.Driver


